# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chat.proto for package 'rpc'

require 'grpc'
require 'chat_pb'

module Rpc
  module Chat
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Chat'

      rpc :SaveMessage, ::Rpc::ChatMessage, ::Rpc::MessageResponse
      rpc :SendMessage, ::Rpc::ChatMessage, ::Rpc::MessageResponse
      rpc :GetLocation, ::Rpc::LocationRequest, stream(::Rpc::LocationResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
